export const ACTIONS = {
        LOAD_PROFILE_REQUEST: "LOAD_PROFILE_REQUEST",
        LOAD_PROFILE_SUCCESS: "LOAD_PROFILE_SUCCESS",
        LOAD_PROFILE_FAILURE: "LOAD_PROFILE_FAILURE",
        LOAD_REPOSITORY_REQUEST: "LOAD_REPOSITORY_REQUEST",
        LOAD_REPOSITORY_SUCCESS: "LOAD_REPOSITORY_SUCCESS",
        LOAD_REPOSITORY_FAILURE: "LOAD_REPOSITORY_FAILURE"
}